name: yoku
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  

  assets:
    - assets/images/logo.png
    - assets/images/numbers/number_one.png
    - assets/images/numbers/number_two.png 
    - assets/images/numbers/number_three.png
    - assets/images/numbers/number_four.png
    - assets/images/numbers/number_five.png
    - assets/images/numbers/number_six.png
    - assets/images/numbers/number_seven.png
    - assets/images/numbers/number_eight.png
    - assets/images/numbers/number_nine.png
    - assets/images/numbers/number_ten.png
    - assets/images/family_members/family_daughter.png
    - assets/images/family_members/family_father.png
    - assets/images/family_members/family_grandfather.png
    - assets/images/family_members/family_grandmother.png
    - assets/images/family_members/family_mother.png
    - assets/images/family_members/family_older_brother.png
    - assets/images/family_members/family_older_sister.png
    - assets/images/family_members/family_son.png
    - assets/images/family_members/family_younger_brother.png
    - assets/images/family_members/family_younger_sister.png
    - assets/images/colors/color_black.png
    - assets/images/colors/color_brown.png
    - assets/images/colors/color_dusty_yellow.png
    - assets/images/colors/color_gray.png
    - assets/images/colors/color_green.png
    - assets/images/colors/color_red.png
    - assets/images/colors/color_white.png
    - assets/images/colors/yellow.png
    - assets/sounds/numbers/number_one_sound.mp3
    - assets/sounds/numbers/number_two_sound.mp3
    - assets/sounds/numbers/number_three_sound.mp3
    - assets/sounds/numbers/number_four_sound.mp3
    - assets/sounds/numbers/number_five_sound.mp3
    - assets/sounds/numbers/number_six_sound.mp3
    - assets/sounds/numbers/number_seven_sound.mp3
    - assets/sounds/numbers/number_eight_sound.mp3
    - assets/sounds/numbers/number_nine_sound.mp3
    - assets/sounds/numbers/number_ten_sound.mp3
    - assets/sounds/family_members/daughter.wav
    - assets/sounds/family_members/father.wav
    - assets/sounds/family_members/grandfather.wav
    - assets/sounds/family_members/grandmother.wav
    - assets/sounds/family_members/oldersister.wav
    - assets/sounds/family_members/son.wav
    - assets/sounds/family_members/olderbother.wav
    - assets/sounds/family_members/mother.wav
    - assets/sounds/family_members/youngersister.wav
    - assets/sounds/family_members/youngerbrohter.wav
    - assets/sounds/colors/black.wav
    - assets/sounds/colors/green.wav
    - assets/sounds/colors/gray.wav
    - assets/sounds/colors/white.wav
    - assets/sounds/colors/red.wav
    - assets/sounds/colors/dusty yellow.wav
    - assets/sounds/colors/yellow.wav
    - assets/sounds/colors/brown.wav
    - assets/sounds/phrases/are_you_coming.wav
    - assets/sounds/phrases/dont_forget_to_subscribe.wav
    - assets/sounds/phrases/how_are_you_feeling.wav
    - assets/sounds/phrases/i_love_anime.wav
    - assets/sounds/phrases/i_love_programming.wav
    - assets/sounds/phrases/programming_is_easy.wav
    - assets/sounds/phrases/what_is_your_name.wav
    - assets/sounds/phrases/where_are_you_going.wav
    - assets/sounds/phrases/yes_im_coming.wav

  fonts:
    - family: DenkOne
      fonts:
        - asset: fonts/DenkOne-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_gravity: fill       # خلي الصورة تمتد لتغطي الشاشة بالكامل
  ios_content_mode: scaleAspectFit # 